<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KolJurusanSekolahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['id_jurusan_sekolah' => 1, 'nama' => 'SMA/ SMU', 'nama_jurusan' => 'IPA'],
            ['id_jurusan_sekolah' => 2, 'nama' => 'SMA/ SMU', 'nama_jurusan' => 'A2 / BIOLOGI'],
            ['id_jurusan_sekolah' => 3, 'nama' => 'SMA/ SMU', 'nama_jurusan' => 'IPS'],
            ['id_jurusan_sekolah' => 4, 'nama' => 'SMA/ SMU', 'nama_jurusan' => 'BAHASA'],
            ['id_jurusan_sekolah' => 10, 'nama' => 'SMK', 'nama_jurusan' => 'ADMINISTRASI PERKANTORAN'],
            ['id_jurusan_sekolah' => 11, 'nama' => 'SMK', 'nama_jurusan' => 'AKUNTANSI'],
            ['id_jurusan_sekolah' => 12, 'nama' => 'SMK', 'nama_jurusan' => 'ALAT BERAT'],
            ['id_jurusan_sekolah' => 13, 'nama' => 'SMK', 'nama_jurusan' => 'ANALISIS KIMIA'],
            ['id_jurusan_sekolah' => 14, 'nama' => 'SMK', 'nama_jurusan' => 'BANGUNAN'],
            ['id_jurusan_sekolah' => 15, 'nama' => 'SMK', 'nama_jurusan' => 'ELEKTRO KOMUNIKASI'],
            ['id_jurusan_sekolah' => 16, 'nama' => 'SMK', 'nama_jurusan' => 'ELEKTRONIKA'],
            ['id_jurusan_sekolah' => 17, 'nama' => 'SMK', 'nama_jurusan' => 'GRAFIKA'],
            ['id_jurusan_sekolah' => 18, 'nama' => 'SMK', 'nama_jurusan' => 'LISTRIK'],
            ['id_jurusan_sekolah' => 19, 'nama' => 'SMK', 'nama_jurusan' => 'LISTRIK INDUSTRI'],
            ['id_jurusan_sekolah' => 20, 'nama' => 'SMK', 'nama_jurusan' => 'MESIN PRODUKSI'],
            ['id_jurusan_sekolah' => 21, 'nama' => 'SMK', 'nama_jurusan' => 'MULTIMEDIA'],
            ['id_jurusan_sekolah' => 22, 'nama' => 'SMK', 'nama_jurusan' => 'NETWORK ACCESS'],
            ['id_jurusan_sekolah' => 23, 'nama' => 'SMK', 'nama_jurusan' => 'OTOMOTIF'],
            ['id_jurusan_sekolah' => 24, 'nama' => 'SMK', 'nama_jurusan' => 'PARIWISATA'],
            ['id_jurusan_sekolah' => 25, 'nama' => 'SMK', 'nama_jurusan' => 'RPL'],
            ['id_jurusan_sekolah' => 26, 'nama' => 'SMK', 'nama_jurusan' => 'SURVEY PEMETAAN'],
            ['id_jurusan_sekolah' => 27, 'nama' => 'SMK', 'nama_jurusan' => 'TATA BUSANA'],
            ['id_jurusan_sekolah' => 28, 'nama' => 'SMK', 'nama_jurusan' => 'TATABOGA'],
            ['id_jurusan_sekolah' => 29, 'nama' => 'SMK', 'nama_jurusan' => 'TEKNIK GEOLOGI PERTAMBANGAN'],
            ['id_jurusan_sekolah' => 30, 'nama' => 'SMK', 'nama_jurusan' => 'TEKNIK JARINGAN KOMPUTER'],
            ['id_jurusan_sekolah' => 31, 'nama' => 'SMK', 'nama_jurusan' => 'TEKNIK KENDARAAN RINGAN'],
            ['id_jurusan_sekolah' => 32, 'nama' => 'SMK', 'nama_jurusan' => 'AVIONIKA'],
            ['id_jurusan_sekolah' => 33, 'nama' => 'SMK', 'nama_jurusan' => 'BANGUNAN KAPAL'],
            ['id_jurusan_sekolah' => 34, 'nama' => 'SMK', 'nama_jurusan' => 'LISTRIK & INSTRUMEN'],
            ['id_jurusan_sekolah' => 35, 'nama' => 'SMK', 'nama_jurusan' => 'MESIN KAPAL'],
            ['id_jurusan_sekolah' => 36, 'nama' => 'SMK', 'nama_jurusan' => 'MOTOR & RANGKA'],
            ['id_jurusan_sekolah' => 37, 'nama' => 'SMK', 'nama_jurusan' => 'TATA BUKU'],
            ['id_jurusan_sekolah' => 38, 'nama' => 'SMK', 'nama_jurusan' => 'TATA NIAGA'],
            ['id_jurusan_sekolah' => 39, 'nama' => 'SMK', 'nama_jurusan' => 'TATA USAHA'],
            ['id_jurusan_sekolah' => 40, 'nama' => 'SMK', 'nama_jurusan' => 'SEKRETARIS'],
            ['id_jurusan_sekolah' => 41, 'nama' => 'SMK', 'nama_jurusan' => 'EKONOMI'],
            ['id_jurusan_sekolah' => 42, 'nama' => 'SMK', 'nama_jurusan' => 'ANALISI KESEHATAN'],
            ['id_jurusan_sekolah' => 43, 'nama' => 'SMK', 'nama_jurusan' => 'FARMASI'],
            ['id_jurusan_sekolah' => 60, 'nama' => 'MA', 'nama_jurusan' => 'IPA'],
            ['id_jurusan_sekolah' => 61, 'nama' => 'MA', 'nama_jurusan' => 'IPS'],
            ['id_jurusan_sekolah' => 62, 'nama' => 'MA', 'nama_jurusan' => 'BAHASA'],
            ['id_jurusan_sekolah' => 63, 'nama' => 'MA', 'nama_jurusan' => 'KEAGAMAN ISLAM'],
            ['id_jurusan_sekolah' => 44, 'nama' => 'SMK', 'nama_jurusan' => 'BROADCASTING'],
            ['id_jurusan_sekolah' => 64, 'nama' => 'SMK', 'nama_jurusan' => 'PERAWAT'],
            ['id_jurusan_sekolah' => 67, 'nama' => 'SMK', 'nama_jurusan' => 'PERTANIAN'],
            ['id_jurusan_sekolah' => 65, 'nama' => 'SMK', 'nama_jurusan' => 'REKAYASA PERANGKAT LUNAK'],
            ['id_jurusan_sekolah' => 66, 'nama' => 'SMK', 'nama_jurusan' => 'TATA KECANTIKAN'],
            ['id_jurusan_sekolah' => 71, 'nama' => 'SMK', 'nama_jurusan' => 'NAOTIKA'],
            ['id_jurusan_sekolah' => 72, 'nama' => 'SMK', 'nama_jurusan' => 'NAUTIKA KAPAL NIAGA'],
            ['id_jurusan_sekolah' => 73, 'nama' => 'SMK', 'nama_jurusan' => 'Seni, Kerajinan dan Pariwisata'],
            ['id_jurusan_sekolah' => 74, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Musik'],
            ['id_jurusan_sekolah' => 5, 'nama' => 'PESANTREN', 'nama_jurusan' => 'PESANTREN'],
            ['id_jurusan_sekolah' => 77, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Konstruksi Baja'],
            ['id_jurusan_sekolah' => 78, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Konstruksi Kayu'],
            ['id_jurusan_sekolah' => 79, 'nama' => 'SMK', 'nama_jurusan' => 'Tekniok Konstruksi Batu dan Beton'],
            ['id_jurusan_sekolah' => 80, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Gambar Bangunan'],
            ['id_jurusan_sekolah' => 81, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Furnitur'],
            ['id_jurusan_sekolah' => 82, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Plambing dan Sanitasi'],
            ['id_jurusan_sekolah' => 83, 'nama' => 'SMK', 'nama_jurusan' => 'Geomatika'],
            ['id_jurusan_sekolah' => 84, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pembangkit Tenaga Listrik'],
            ['id_jurusan_sekolah' => 85, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Jaringan Tenaga Listrik'],
            ['id_jurusan_sekolah' => 86, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Instalasi Pemanfaatan Tenaga Listrik'],
            ['id_jurusan_sekolah' => 87, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Otomasi Industri'],
            ['id_jurusan_sekolah' => 88, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pendingin dan Tata Udara'],
            ['id_jurusan_sekolah' => 89, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pemesinan'],
            ['id_jurusan_sekolah' => 90, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pengelasan'],
            ['id_jurusan_sekolah' => 91, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Fabrikasi Logam'],
            ['id_jurusan_sekolah' => 92, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pengecoran Logam'],
            ['id_jurusan_sekolah' => 93, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pemeliharaan Mekanik Industri'],
            ['id_jurusan_sekolah' => 94, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Gambar Mesin'],
            ['id_jurusan_sekolah' => 95, 'nama' => 'SMK', 'nama_jurusan' => 'Pemeliharaan dan Perbaikan Motor dan Rangka Pesawa'],
            ['id_jurusan_sekolah' => 96, 'nama' => 'SMK', 'nama_jurusan' => 'Pemesinan Pesawat Udara (Aircraft Machining)'],
            ['id_jurusan_sekolah' => 97, 'nama' => 'SMK', 'nama_jurusan' => 'Konstruksi Badan Pesawat Udara (Aircraft Sheet Metal Forming)'],
            ['id_jurusan_sekolah' => 98, 'nama' => 'SMK', 'nama_jurusan' => 'Konstruksi Rangka Pesawat Udara (Airframe Mechanic)'],
            ['id_jurusan_sekolah' => 99, 'nama' => 'SMK', 'nama_jurusan' => 'Kelistrikan Pesawat Udara (Aircraft Electricity)'],
            ['id_jurusan_sekolah' => 100, 'nama' => 'SMK', 'nama_jurusan' => 'Elektronika Pesawat Udara (Aviation Electronics)'],
            ['id_jurusan_sekolah' => 101, 'nama' => 'SMK', 'nama_jurusan' => 'Pemeliharaan dan Perbaikan Instrumen Elektronika P'],
            ['id_jurusan_sekolah' => 102, 'nama' => 'SMK', 'nama_jurusan' => 'Persiapan Grafika'],
            ['id_jurusan_sekolah' => 103, 'nama' => 'SMK', 'nama_jurusan' => 'Produksi Grafika'],
            ['id_jurusan_sekolah' => 104, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Instrumentasi Logam'],
            ['id_jurusan_sekolah' => 105, 'nama' => 'SMK', 'nama_jurusan' => 'Kontrol Proses'],
            ['id_jurusan_sekolah' => 106, 'nama' => 'SMK', 'nama_jurusan' => 'Kontrol Mekanik'],
            ['id_jurusan_sekolah' => 107, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pelayanan Produksi'],
            ['id_jurusan_sekolah' => 108, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pergudangan'],
            ['id_jurusan_sekolah' => 109, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pemintalan Serat Buatan'],
            ['id_jurusan_sekolah' => 110, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pembuatan Benang'],
            ['id_jurusan_sekolah' => 111, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pembuatan Kain'],
            ['id_jurusan_sekolah' => 112, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Penyempurnaan Tekstil'],
            ['id_jurusan_sekolah' => 113, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Produksi Minyak dan Gas'],
            ['id_jurusan_sekolah' => 114, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pemboran Minyak dan Gas'],
            ['id_jurusan_sekolah' => 115, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pengolahan Minyak, Gas dan Petrokimia'],
            ['id_jurusan_sekolah' => 116, 'nama' => 'SMK', 'nama_jurusan' => 'Geologi Pertambangan'],
            ['id_jurusan_sekolah' => 117, 'nama' => 'SMK', 'nama_jurusan' => 'Kimia Analisis'],
            ['id_jurusan_sekolah' => 118, 'nama' => 'SMK', 'nama_jurusan' => 'Kimia Industri'],
            ['id_jurusan_sekolah' => 119, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pengolahan Logam'],
            ['id_jurusan_sekolah' => 120, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Proses Industri'],
            ['id_jurusan_sekolah' => 121, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Otomotif'],
            ['id_jurusan_sekolah' => 122, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Otomasi'],
            ['id_jurusan_sekolah' => 123, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pengelasan'],
            ['id_jurusan_sekolah' => 124, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Telekomunikasi'],
            ['id_jurusan_sekolah' => 125, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Jaringan Telekomunikasi'],
            ['id_jurusan_sekolah' => 126, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pengelolaan Sumber Daya Alam'],
            ['id_jurusan_sekolah' => 127, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pertambangan'],
            ['id_jurusan_sekolah' => 128, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Mineral dan Geologi'],
            ['id_jurusan_sekolah' => 129, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Pemurnian Logam'],
            ['id_jurusan_sekolah' => 130, 'nama' => 'SMK', 'nama_jurusan' => 'Manajemen Perdagangan'],
            ['id_jurusan_sekolah' => 131, 'nama' => 'SMK', 'nama_jurusan' => 'Manajemen Pemasaran'],
            ['id_jurusan_sekolah' => 132, 'nama' => 'SMK', 'nama_jurusan' => 'Manajemen Keuangan'],
            ['id_jurusan_sekolah' => 133, 'nama' => 'SMK', 'nama_jurusan' => 'Manajemen Usaha Pariwisata'],
            ['id_jurusan_sekolah' => 134, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Penerbangan'],
            ['id_jurusan_sekolah' => 135, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Keuangan dan Perbankan'],
            ['id_jurusan_sekolah' => 136, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Multimedia'],
            ['id_jurusan_sekolah' => 137, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik IT'],
            ['id_jurusan_sekolah' => 138, 'nama' => 'SMK', 'nama_jurusan' => 'Teknik Elektronik dan Mikrokontroler'],
            ['id_jurusan_sekolah' => 139, 'nama' => 'SMK', 'nama_jurusan' => 'Desain Komunikasi Visual'],
            ['id_jurusan_sekolah' => 140, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Budaya'],
            ['id_jurusan_sekolah' => 141, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Grafis'],
            ['id_jurusan_sekolah' => 142, 'nama' => 'SMK', 'nama_jurusan' => 'Desain Mode'],
            ['id_jurusan_sekolah' => 143, 'nama' => 'SMK', 'nama_jurusan' => 'Desain Interior'],
            ['id_jurusan_sekolah' => 144, 'nama' => 'SMK', 'nama_jurusan' => 'Desain Produk'],
            ['id_jurusan_sekolah' => 145, 'nama' => 'SMK', 'nama_jurusan' => 'Pendidikan Kesenian'],
            ['id_jurusan_sekolah' => 146, 'nama' => 'SMK', 'nama_jurusan' => 'Pendidikan Musik'],
            ['id_jurusan_sekolah' => 147, 'nama' => 'SMK', 'nama_jurusan' => 'Pendidikan Tari'],
            ['id_jurusan_sekolah' => 148, 'nama' => 'SMK', 'nama_jurusan' => 'Pendidikan Desain'],
            ['id_jurusan_sekolah' => 149, 'nama' => 'SMK', 'nama_jurusan' => 'Pendidikan Seni Rupa'],
            ['id_jurusan_sekolah' => 150, 'nama' => 'SMK', 'nama_jurusan' => 'Pendidikan Film'],
            ['id_jurusan_sekolah' => 151, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Lukis'],
            ['id_jurusan_sekolah' => 152, 'nama' => 'SMK', 'nama_jurusan' => 'Desain Animasi'],
            ['id_jurusan_sekolah' => 153, 'nama' => 'SMK', 'nama_jurusan' => 'Pendidikan Kerajinan'],
            ['id_jurusan_sekolah' => 154, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Kriya'],
            ['id_jurusan_sekolah' => 155, 'nama' => 'SMK', 'nama_jurusan' => 'Seni dan Kerajinan'],
            ['id_jurusan_sekolah' => 156, 'nama' => 'SMK', 'nama_jurusan' => 'Pendidikan Kerajinan'],
            ['id_jurusan_sekolah' => 157, 'nama' => 'SMK', 'nama_jurusan' => 'Desain Percetakan'],
            ['id_jurusan_sekolah' => 158, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Peran'],
            ['id_jurusan_sekolah' => 159, 'nama' => 'SMK', 'nama_jurusan' => 'Teater'],
            ['id_jurusan_sekolah' => 160, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Pahat'],
            ['id_jurusan_sekolah' => 161, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Instalasi'],
            ['id_jurusan_sekolah' => 162, 'nama' => 'SMK', 'nama_jurusan' => 'Desain Graffiti'],
            ['id_jurusan_sekolah' => 163, 'nama' => 'SMK', 'nama_jurusan' => 'Desain Website'],
            ['id_jurusan_sekolah' => 164, 'nama' => 'SMK', 'nama_jurusan' => 'Pengembangan Aplikasi Mobile'],
            ['id_jurusan_sekolah' => 165, 'nama' => 'SMK', 'nama_jurusan' => 'Pengembangan Perangkat Lunak'],
            ['id_jurusan_sekolah' => 166, 'nama' => 'SMK', 'nama_jurusan' => 'Perancangan Grafis Digital'],
            ['id_jurusan_sekolah' => 167, 'nama' => 'SMK', 'nama_jurusan' => 'Pemrograman Perangkat Lunak'],
            ['id_jurusan_sekolah' => 168, 'nama' => 'SMK', 'nama_jurusan' => 'Pengolahan Citra Digital'],
            ['id_jurusan_sekolah' => 169, 'nama' => 'SMK', 'nama_jurusan' => 'Penyiaran Televisi'],
            ['id_jurusan_sekolah' => 170, 'nama' => 'SMK', 'nama_jurusan' => 'Penyiaran Radio'],
            ['id_jurusan_sekolah' => 171, 'nama' => 'SMK', 'nama_jurusan' => 'Produksi Televisi'],
            ['id_jurusan_sekolah' => 172, 'nama' => 'SMK', 'nama_jurusan' => 'Media Digital'],
            ['id_jurusan_sekolah' => 173, 'nama' => 'SMK', 'nama_jurusan' => 'Pengolahan Audio'],
            ['id_jurusan_sekolah' => 174, 'nama' => 'SMK', 'nama_jurusan' => 'Fotografi Digital'],
            ['id_jurusan_sekolah' => 175, 'nama' => 'SMK', 'nama_jurusan' => 'Jurnalistik'],
            ['id_jurusan_sekolah' => 176, 'nama' => 'SMK', 'nama_jurusan' => 'Video Editing'],
            ['id_jurusan_sekolah' => 177, 'nama' => 'SMK', 'nama_jurusan' => 'Periklanan'],
            ['id_jurusan_sekolah' => 178, 'nama' => 'SMK', 'nama_jurusan' => 'Manajemen Periklanan'],
            ['id_jurusan_sekolah' => 179, 'nama' => 'SMK', 'nama_jurusan' => 'Komunikasi Visual'],
            ['id_jurusan_sekolah' => 180, 'nama' => 'SMK', 'nama_jurusan' => 'Teknologi Informasi dan Komunikasi'],
            ['id_jurusan_sekolah' => 181, 'nama' => 'SMK', 'nama_jurusan' => 'Desain Teknik Otomotif'],
            ['id_jurusan_sekolah' => 182, 'nama' => 'SMK', 'nama_jurusan' => 'Desain Teknik Mesin'],
            ['id_jurusan_sekolah' => 183, 'nama' => 'SMK', 'nama_jurusan' => 'Jasa Boga'],
            ['id_jurusan_sekolah' => 184, 'nama' => 'SMK', 'nama_jurusan' => 'Patiseri'],
            ['id_jurusan_sekolah' => 185, 'nama' => 'SMK', 'nama_jurusan' => 'Tata Kecantikan Rambut'],
            ['id_jurusan_sekolah' => 186, 'nama' => 'SMK', 'nama_jurusan' => 'Tata Kecantikan Kulit'],
            ['id_jurusan_sekolah' => 188, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Lukis'],
            ['id_jurusan_sekolah' => 189, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Patung'],
            ['id_jurusan_sekolah' => 190, 'nama' => 'SMK', 'nama_jurusan' => 'Desain Komunikasi Visual'],
            ['id_jurusan_sekolah' => 191, 'nama' => 'SMK', 'nama_jurusan' => 'Desain Interior'],
            ['id_jurusan_sekolah' => 192, 'nama' => 'SMK', 'nama_jurusan' => 'Animasi'],
            ['id_jurusan_sekolah' => 193, 'nama' => 'SMK', 'nama_jurusan' => 'Desain dan Produksi Kriya Tekstil'],
            ['id_jurusan_sekolah' => 194, 'nama' => 'SMK', 'nama_jurusan' => 'Desain dan Produksi Kriya Kulit'],
            ['id_jurusan_sekolah' => 195, 'nama' => 'SMK', 'nama_jurusan' => 'Desain dan Produksi Kriya Keramik'],
            ['id_jurusan_sekolah' => 196, 'nama' => 'SMK', 'nama_jurusan' => 'Desain dan Produksi Kriya Logam'],
            ['id_jurusan_sekolah' => 197, 'nama' => 'SMK', 'nama_jurusan' => 'Desain dan Produksi Kriya Kayu'],
            ['id_jurusan_sekolah' => 198, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Musik Klasik'],
            ['id_jurusan_sekolah' => 199, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Musik Non Klasik'],
            ['id_jurusan_sekolah' => 200, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Tari'],
            ['id_jurusan_sekolah' => 201, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Karawitan'],
            ['id_jurusan_sekolah' => 202, 'nama' => 'SMK', 'nama_jurusan' => 'Seni Pedalangan'],
            ['id_jurusan_sekolah' => 203, 'nama' => 'SMK', 'nama_jurusan' => 'Pemeranan'],
            ['id_jurusan_sekolah' => 204, 'nama' => 'SMK', 'nama_jurusan' => 'Tata Artistik']
        ];

        DB::table('kol_jurusan_sekolah')->insert($data);
    }
}
