<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KolJurusanSekolahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['id' => 1, 'asal_sekolah' => 'SMA/ SMU', 'nama' => 'IPA'],
            ['id' => 2, 'asal_sekolah' => 'SMA/ SMU', 'nama' => 'A2 / BIOLOGI'],
            ['id' => 3, 'asal_sekolah' => 'SMA/ SMU', 'nama' => 'IPS'],
            ['id' => 4, 'asal_sekolah' => 'SMA/ SMU', 'nama' => 'BAHASA'],
            ['id' => 10, 'asal_sekolah' => 'SMK', 'nama' => 'ADMINISTRASI PERKANTORAN'],
            ['id' => 11, 'asal_sekolah' => 'SMK', 'nama' => 'AKUNTANSI'],
            ['id' => 12, 'asal_sekolah' => 'SMK', 'nama' => 'ALAT BERAT'],
            ['id' => 13, 'asal_sekolah' => 'SMK', 'nama' => 'ANALISIS KIMIA'],
            ['id' => 14, 'asal_sekolah' => 'SMK', 'nama' => 'BANGUNAN'],
            ['id' => 15, 'asal_sekolah' => 'SMK', 'nama' => 'ELEKTRO KOMUNIKASI'],
            ['id' => 16, 'asal_sekolah' => 'SMK', 'nama' => 'ELEKTRONIKA'],
            ['id' => 17, 'asal_sekolah' => 'SMK', 'nama' => 'GRAFIKA'],
            ['id' => 18, 'asal_sekolah' => 'SMK', 'nama' => 'LISTRIK'],
            ['id' => 19, 'asal_sekolah' => 'SMK', 'nama' => 'LISTRIK INDUSTRI'],
            ['id' => 20, 'asal_sekolah' => 'SMK', 'nama' => 'MESIN PRODUKSI'],
            ['id' => 21, 'asal_sekolah' => 'SMK', 'nama' => 'MULTIMEDIA'],
            ['id' => 22, 'asal_sekolah' => 'SMK', 'nama' => 'NETWORK ACCESS'],
            ['id' => 23, 'asal_sekolah' => 'SMK', 'nama' => 'OTOMOTIF'],
            ['id' => 24, 'asal_sekolah' => 'SMK', 'nama' => 'PARIWISATA'],
            ['id' => 25, 'asal_sekolah' => 'SMK', 'nama' => 'RPL'],
            ['id' => 26, 'asal_sekolah' => 'SMK', 'nama' => 'SURVEY PEMETAAN'],
            ['id' => 27, 'asal_sekolah' => 'SMK', 'nama' => 'TATA BUSANA'],
            ['id' => 28, 'asal_sekolah' => 'SMK', 'nama' => 'TATABOGA'],
            ['id' => 29, 'asal_sekolah' => 'SMK', 'nama' => 'TEKNIK GEOLOGI PERTAMBANGAN'],
            ['id' => 30, 'asal_sekolah' => 'SMK', 'nama' => 'TEKNIK JARINGAN KOMPUTER'],
            ['id' => 31, 'asal_sekolah' => 'SMK', 'nama' => 'TEKNIK KENDARAAN RINGAN'],
            ['id' => 32, 'asal_sekolah' => 'SMK', 'nama' => 'AVIONIKA'],
            ['id' => 33, 'asal_sekolah' => 'SMK', 'nama' => 'BANGUNAN KAPAL'],
            ['id' => 34, 'asal_sekolah' => 'SMK', 'nama' => 'LISTRIK & INSTRUMEN'],
            ['id' => 35, 'asal_sekolah' => 'SMK', 'nama' => 'MESIN KAPAL'],
            ['id' => 36, 'asal_sekolah' => 'SMK', 'nama' => 'MOTOR & RANGKA'],
            ['id' => 37, 'asal_sekolah' => 'SMK', 'nama' => 'TATA BUKU'],
            ['id' => 38, 'asal_sekolah' => 'SMK', 'nama' => 'TATA NIAGA'],
            ['id' => 39, 'asal_sekolah' => 'SMK', 'nama' => 'TATA USAHA'],
            ['id' => 40, 'asal_sekolah' => 'SMK', 'nama' => 'SEKRETARIS'],
            ['id' => 41, 'asal_sekolah' => 'SMK', 'nama' => 'EKONOMI'],
            ['id' => 42, 'asal_sekolah' => 'SMK', 'nama' => 'ANALISI KESEHATAN'],
            ['id' => 43, 'asal_sekolah' => 'SMK', 'nama' => 'FARMASI'],
            ['id' => 60, 'asal_sekolah' => 'MA', 'nama' => 'IPA'],
            ['id' => 61, 'asal_sekolah' => 'MA', 'nama' => 'IPS'],
            ['id' => 62, 'asal_sekolah' => 'MA', 'nama' => 'BAHASA'],
            ['id' => 63, 'asal_sekolah' => 'MA', 'nama' => 'KEAGAMAN ISLAM'],
            ['id' => 44, 'asal_sekolah' => 'SMK', 'nama' => 'BROADCASTING'],
            ['id' => 64, 'asal_sekolah' => 'SMK', 'nama' => 'PERAWAT'],
            ['id' => 67, 'asal_sekolah' => 'SMK', 'nama' => 'PERTANIAN'],
            ['id' => 65, 'asal_sekolah' => 'SMK', 'nama' => 'REKAYASA PERANGKAT LUNAK'],
            ['id' => 66, 'asal_sekolah' => 'SMK', 'nama' => 'TATA KECANTIKAN'],
            ['id' => 71, 'asal_sekolah' => 'SMK', 'nama' => 'NAOTIKA'],
            ['id' => 72, 'asal_sekolah' => 'SMK', 'nama' => 'NAUTIKA KAPAL NIAGA'],
            ['id' => 73, 'asal_sekolah' => 'SMK', 'nama' => 'Seni, Kerajinan dan Pariwisata'],
            ['id' => 74, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Musik'],
            ['id' => 5, 'asal_sekolah' => 'PESANTREN', 'nama' => 'PESANTREN'],
            ['id' => 77, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Konstruksi Baja'],
            ['id' => 78, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Konstruksi Kayu'],
            ['id' => 79, 'asal_sekolah' => 'SMK', 'nama' => 'Tekniok Konstruksi Batu dan Beton'],
            ['id' => 80, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Gambar Bangunan'],
            ['id' => 81, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Furnitur'],
            ['id' => 82, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Plambing dan Sanitasi'],
            ['id' => 83, 'asal_sekolah' => 'SMK', 'nama' => 'Geomatika'],
            ['id' => 84, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pembangkit Tenaga Listrik'],
            ['id' => 85, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Jaringan Tenaga Listrik'],
            ['id' => 86, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Instalasi Pemanfaatan Tenaga Listrik'],
            ['id' => 87, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Otomasi Industri'],
            ['id' => 88, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pendingin dan Tata Udara'],
            ['id' => 89, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pemesinan'],
            ['id' => 90, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pengelasan'],
            ['id' => 91, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Fabrikasi Logam'],
            ['id' => 92, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pengecoran Logam'],
            ['id' => 93, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pemeliharaan Mekanik Industri'],
            ['id' => 94, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Gambar Mesin'],
            ['id' => 95, 'asal_sekolah' => 'SMK', 'nama' => 'Pemeliharaan dan Perbaikan Motor dan Rangka Pesawa'],
            ['id' => 96, 'asal_sekolah' => 'SMK', 'nama' => 'Pemesinan Pesawat Udara (Aircraft Machining)'],
            ['id' => 97, 'asal_sekolah' => 'SMK', 'nama' => 'Konstruksi Badan Pesawat Udara (Aircraft Sheet Metal Forming)'],
            ['id' => 98, 'asal_sekolah' => 'SMK', 'nama' => 'Konstruksi Rangka Pesawat Udara (Airframe Mechanic)'],
            ['id' => 99, 'asal_sekolah' => 'SMK', 'nama' => 'Kelistrikan Pesawat Udara (Aircraft Electricity)'],
            ['id' => 100, 'asal_sekolah' => 'SMK', 'nama' => 'Elektronika Pesawat Udara (Aviation Electronics)'],
            ['id' => 101, 'asal_sekolah' => 'SMK', 'nama' => 'Pemeliharaan dan Perbaikan Instrumen Elektronika P'],
            ['id' => 102, 'asal_sekolah' => 'SMK', 'nama' => 'Persiapan Grafika'],
            ['id' => 103, 'asal_sekolah' => 'SMK', 'nama' => 'Produksi Grafika'],
            ['id' => 104, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Instrumentasi Logam'],
            ['id' => 105, 'asal_sekolah' => 'SMK', 'nama' => 'Kontrol Proses'],
            ['id' => 106, 'asal_sekolah' => 'SMK', 'nama' => 'Kontrol Mekanik'],
            ['id' => 107, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pelayanan Produksi'],
            ['id' => 108, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pergudangan'],
            ['id' => 109, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pemintalan Serat Buatan'],
            ['id' => 110, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pembuatan Benang'],
            ['id' => 111, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pembuatan Kain'],
            ['id' => 112, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Penyempurnaan Tekstil'],
            ['id' => 113, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Produksi Minyak dan Gas'],
            ['id' => 114, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pemboran Minyak dan Gas'],
            ['id' => 115, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pengolahan Minyak, Gas dan Petrokimia'],
            ['id' => 116, 'asal_sekolah' => 'SMK', 'nama' => 'Geologi Pertambangan'],
            ['id' => 117, 'asal_sekolah' => 'SMK', 'nama' => 'Kimia Analisis'],
            ['id' => 118, 'asal_sekolah' => 'SMK', 'nama' => 'Kimia Industri'],
            ['id' => 119, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pengolahan Logam'],
            ['id' => 120, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Proses Industri'],
            ['id' => 121, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Otomotif'],
            ['id' => 122, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Otomasi'],
            ['id' => 123, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pengelasan'],
            ['id' => 124, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Telekomunikasi'],
            ['id' => 125, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Jaringan Telekomunikasi'],
            ['id' => 126, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pengelolaan Sumber Daya Alam'],
            ['id' => 127, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pertambangan'],
            ['id' => 128, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Mineral dan Geologi'],
            ['id' => 129, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Pemurnian Logam'],
            ['id' => 130, 'asal_sekolah' => 'SMK', 'nama' => 'Manajemen Perdagangan'],
            ['id' => 131, 'asal_sekolah' => 'SMK', 'nama' => 'Manajemen Pemasaran'],
            ['id' => 132, 'asal_sekolah' => 'SMK', 'nama' => 'Manajemen Keuangan'],
            ['id' => 133, 'asal_sekolah' => 'SMK', 'nama' => 'Manajemen Usaha Pariwisata'],
            ['id' => 134, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Penerbangan'],
            ['id' => 135, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Keuangan dan Perbankan'],
            ['id' => 136, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Multimedia'],
            ['id' => 137, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik IT'],
            ['id' => 138, 'asal_sekolah' => 'SMK', 'nama' => 'Teknik Elektronik dan Mikrokontroler'],
            ['id' => 139, 'asal_sekolah' => 'SMK', 'nama' => 'Desain Komunikasi Visual'],
            ['id' => 140, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Budaya'],
            ['id' => 141, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Grafis'],
            ['id' => 142, 'asal_sekolah' => 'SMK', 'nama' => 'Desain Mode'],
            ['id' => 143, 'asal_sekolah' => 'SMK', 'nama' => 'Desain Interior'],
            ['id' => 144, 'asal_sekolah' => 'SMK', 'nama' => 'Desain Produk'],
            ['id' => 145, 'asal_sekolah' => 'SMK', 'nama' => 'Pendidikan Kesenian'],
            ['id' => 146, 'asal_sekolah' => 'SMK', 'nama' => 'Pendidikan Musik'],
            ['id' => 147, 'asal_sekolah' => 'SMK', 'nama' => 'Pendidikan Tari'],
            ['id' => 148, 'asal_sekolah' => 'SMK', 'nama' => 'Pendidikan Desain'],
            ['id' => 149, 'asal_sekolah' => 'SMK', 'nama' => 'Pendidikan Seni Rupa'],
            ['id' => 150, 'asal_sekolah' => 'SMK', 'nama' => 'Pendidikan Film'],
            ['id' => 151, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Lukis'],
            ['id' => 152, 'asal_sekolah' => 'SMK', 'nama' => 'Desain Animasi'],
            ['id' => 153, 'asal_sekolah' => 'SMK', 'nama' => 'Pendidikan Kerajinan'],
            ['id' => 154, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Kriya'],
            ['id' => 155, 'asal_sekolah' => 'SMK', 'nama' => 'Seni dan Kerajinan'],
            ['id' => 156, 'asal_sekolah' => 'SMK', 'nama' => 'Pendidikan Kerajinan'],
            ['id' => 157, 'asal_sekolah' => 'SMK', 'nama' => 'Desain Percetakan'],
            ['id' => 158, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Peran'],
            ['id' => 159, 'asal_sekolah' => 'SMK', 'nama' => 'Teater'],
            ['id' => 160, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Pahat'],
            ['id' => 161, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Instalasi'],
            ['id' => 162, 'asal_sekolah' => 'SMK', 'nama' => 'Desain Graffiti'],
            ['id' => 163, 'asal_sekolah' => 'SMK', 'nama' => 'Desain Website'],
            ['id' => 164, 'asal_sekolah' => 'SMK', 'nama' => 'Pengembangan Aplikasi Mobile'],
            ['id' => 165, 'asal_sekolah' => 'SMK', 'nama' => 'Pengembangan Perangkat Lunak'],
            ['id' => 166, 'asal_sekolah' => 'SMK', 'nama' => 'Perancangan Grafis Digital'],
            ['id' => 167, 'asal_sekolah' => 'SMK', 'nama' => 'Pemrograman Perangkat Lunak'],
            ['id' => 168, 'asal_sekolah' => 'SMK', 'nama' => 'Pengolahan Citra Digital'],
            ['id' => 169, 'asal_sekolah' => 'SMK', 'nama' => 'Penyiaran Televisi'],
            ['id' => 170, 'asal_sekolah' => 'SMK', 'nama' => 'Penyiaran Radio'],
            ['id' => 171, 'asal_sekolah' => 'SMK', 'nama' => 'Produksi Televisi'],
            ['id' => 172, 'asal_sekolah' => 'SMK', 'nama' => 'Media Digital'],
            ['id' => 173, 'asal_sekolah' => 'SMK', 'nama' => 'Pengolahan Audio'],
            ['id' => 174, 'asal_sekolah' => 'SMK', 'nama' => 'Fotografi Digital'],
            ['id' => 175, 'asal_sekolah' => 'SMK', 'nama' => 'Jurnalistik'],
            ['id' => 176, 'asal_sekolah' => 'SMK', 'nama' => 'Video Editing'],
            ['id' => 177, 'asal_sekolah' => 'SMK', 'nama' => 'Periklanan'],
            ['id' => 178, 'asal_sekolah' => 'SMK', 'nama' => 'Manajemen Periklanan'],
            ['id' => 179, 'asal_sekolah' => 'SMK', 'nama' => 'Komunikasi Visual'],
            ['id' => 180, 'asal_sekolah' => 'SMK', 'nama' => 'Teknologi Informasi dan Komunikasi'],
            ['id' => 181, 'asal_sekolah' => 'SMK', 'nama' => 'Desain Teknik Otomotif'],
            ['id' => 182, 'asal_sekolah' => 'SMK', 'nama' => 'Desain Teknik Mesin'],
            ['id' => 183, 'asal_sekolah' => 'SMK', 'nama' => 'Jasa Boga'],
            ['id' => 184, 'asal_sekolah' => 'SMK', 'nama' => 'Patiseri'],
            ['id' => 185, 'asal_sekolah' => 'SMK', 'nama' => 'Tata Kecantikan Rambut'],
            ['id' => 186, 'asal_sekolah' => 'SMK', 'nama' => 'Tata Kecantikan Kulit'],
            ['id' => 188, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Lukis'],
            ['id' => 189, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Patung'],
            ['id' => 190, 'asal_sekolah' => 'SMK', 'nama' => 'Desain Komunikasi Visual'],
            ['id' => 191, 'asal_sekolah' => 'SMK', 'nama' => 'Desain Interior'],
            ['id' => 192, 'asal_sekolah' => 'SMK', 'nama' => 'Animasi'],
            ['id' => 193, 'asal_sekolah' => 'SMK', 'nama' => 'Desain dan Produksi Kriya Tekstil'],
            ['id' => 194, 'asal_sekolah' => 'SMK', 'nama' => 'Desain dan Produksi Kriya Kulit'],
            ['id' => 195, 'asal_sekolah' => 'SMK', 'nama' => 'Desain dan Produksi Kriya Keramik'],
            ['id' => 196, 'asal_sekolah' => 'SMK', 'nama' => 'Desain dan Produksi Kriya Logam'],
            ['id' => 197, 'asal_sekolah' => 'SMK', 'nama' => 'Desain dan Produksi Kriya Kayu'],
            ['id' => 198, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Musik Klasik'],
            ['id' => 199, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Musik Non Klasik'],
            ['id' => 200, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Tari'],
            ['id' => 201, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Karawitan'],
            ['id' => 202, 'asal_sekolah' => 'SMK', 'nama' => 'Seni Pedalangan'],
            ['id' => 203, 'asal_sekolah' => 'SMK', 'nama' => 'Pemeranan'],
            ['id' => 204, 'asal_sekolah' => 'SMK', 'nama' => 'Tata Artistik']
        ];

        DB::table('kol_jurusan_sekolah')->insert($data);
    }
}
